# Generated by Django 3.0.5 on 2020-05-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='meme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Meme'),
            preserve_default=False,
        ),
    ]
