# Generated by Django 3.0.5 on 2020-05-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_comments_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
